notify = ["uv", "run", "~/.codex/notification.py"]
model = "gpt-5.1-codex-max"
model_reasoning_effort = "high"

[features]
web_search_request = true

# [profiles.pro]
# model = "gpt-5.1-pro"
# model_reasoning_effort = "high"
# # approval_policy = "never"

[profiles.fast]
model = "gpt-5.1-codex-max"
model_reasoning_effort = "medium"

[profiles.xhigh]
model = "gpt-5.1-codex-max"
model_reasoning_effort = "xhigh"

[profiles.normal]
model = "gpt-5.1-codex"
model_reasoning_effort = "high"

[profiles.normal-fast]
model = "gpt-5.1-codex"
model_reasoning_effort = "medium"

[profiles.normal-xhigh]
model = "gpt-5.1-codex"
model_reasoning_effort = "xhigh"
