[settings]
idiomatic_version_file_enable_tools = ["node"]
auto_install = true

[tools]
# npmのglobalはmiseで管理する
"npm:@anthropic-ai/claude-code" = "2.0.46"
"npm:@google/gemini-cli" = "0.16.0"
"npm:@openai/codex" = "0.58.0"
"npm:ccusage" = "17.1.6"
"npm:@typescript/native-preview" = "7.0.0-dev.20251118.1"
# "1password-cli" = "2.31.1"
