[settings]
idiomatic_version_file_enable_tools = ["node"]
auto_install = true

[tools]
# npmのglobalはmiseで管理する
"npm:@anthropic-ai/claude-code" = "2.0.76"
"npm:@google/gemini-cli" = "0.22.2"
"npm:@openai/codex" = "0.77.0"
"npm:ccusage" = "17.2.0"
"npm:@typescript/native-preview" = "7.0.0-dev.20251222.1"
"npm:cc-sdd" = "2.0.3"
