[settings]
idiomatic_version_file_enable_tools = ["node"]
auto_install = true

[tools]
# npmのglobalはmiseで管理する
"npm:@anthropic-ai/claude-code" = "2.0.49"
"npm:@google/gemini-cli" = "0.17.0"
"npm:@openai/codex" = "0.61.0"
"npm:ccusage" = "17.1.6"
"npm:@typescript/native-preview" = "7.0.0-dev.20251121.1"
"npm:cc-sdd" = "2.0.3"
# "1password-cli" = "2.31.1"
