[settings]
idiomatic_version_file_enable_tools = ["node"]
auto_install = true

[tools]
# npmのglobalはmiseで管理する
"npm:@anthropic-ai/claude-code" = "2.0.37"
"npm:@google/gemini-cli" = "0.13.0"
"npm:@openai/codex" = "0.57.0"
"npm:ccusage" = "17.1.4"
"npm:@typescript/native-preview" = "7.0.0-dev.20251110.1"
"1password-cli" = "2.31.1"
