[settings]
idiomatic_version_file_enable_tools = ["node"]
auto_install = true

[tools]
# npmのglobalはmiseで管理する
"npm:@anthropic-ai/claude-code" = "2.0.50"
"npm:@google/gemini-cli" = "0.17.1"
"npm:@openai/codex" = "0.63.0"
"npm:ccusage" = "17.1.6"
"npm:@typescript/native-preview" = "7.0.0-dev.20251124.1"
"npm:cc-sdd" = "2.0.3"
